---
http_interactions:
- request:
    method: get
    uri: http://localhost:8111/guestAuth/app/rest/7.0/buildTypes/id:bt2/artifact-dependencies
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json; charset=utf-8
      User-Agent:
      - TeamCity Ruby Client 0.0.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - Apache-Coyote/1.1
      Set-Cookie:
      - JSESSIONID=331D2454B543F0E251A394FCED6419F3; Path=/; HttpOnly
      - RememberMe=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; HttpOnly
      Pragma:
      - no-cache
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Cache-Control:
      - no-cache
      - no-store
      Content-Type:
      - application/json
      Transfer-Encoding:
      - chunked
      Date:
      - Tue, 23 Apr 2013 15:14:22 GMT
    body:
      encoding: US-ASCII
      string: ! '{"artifact-dependency":[{"id":"0","type":"artifact_dependency","properties":{"property":[{"name":"cleanDestinationDirectory","value":"false"},{"name":"pathRules","value":"+:version.txt"},{"name":"revisionName","value":"sameChainOrLastFinished"},{"name":"revisionValue","value":"latest.sameChainOrLastFinished"},{"name":"source_buildTypeId","value":"bt3"}]}}]}'
    http_version: 
  recorded_at: Tue, 23 Apr 2013 15:14:23 GMT
recorded_with: VCR 2.4.0
