---
http_interactions:
- request:
    method: get
    uri: http://localhost:8111/guestAuth/app/rest/buildTypes/BuildTypeTests_GetBuildTypeConfigTests/branches
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - TeamCity Ruby Client 1.2.0
      Accept:
      - application/json; charset=utf-8
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - Apache-Coyote/1.1
      Set-Cookie:
      - RememberMe=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; HttpOnly
      - TCSESSIONID=F3F286B29E25E387B4F1448AB8462DF7; Path=/; HttpOnly
      Pragma:
      - no-cache
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Cache-Control:
      - no-cache
      - no-store
      Content-Type:
      - application/json
      Transfer-Encoding:
      - chunked
      Date:
      - Fri, 27 Dec 2013 20:36:36 GMT
    body:
      encoding: US-ASCII
      string: ! '{"branch":[{"name":"refs/heads/master","default":true}]}'
    http_version: 
  recorded_at: Fri, 27 Dec 2013 20:36:36 GMT
recorded_with: VCR 2.4.0
